stop execution when homework/quiz cannot be found

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -30,6 +30,11 @@ run() {
     eval $*
 }
 
+fail() {
+    error $*
+    exit 1
+}
+
 strip_colors() {
     while read -r line
     do
@@ -178,14 +183,6 @@ clone_or_update_repos() {
     done < $GTB_STUDENTS_FILE
 }
 
-assert_repo_exists() {
-    if [[ ! -f $GTB_STUDENTS_FILE ]]
-    then
-        error "Cannot find students file: '$GTB_STUDENTS_FILE'."
-        exit 1
-    fi
-}
-
 assert_students_file_exists() {
     if [[ ! -f $GTB_STUDENTS_FILE ]]
     then
@@ -294,8 +291,8 @@ _gtb_test() {
     local HOMEWORK_TESTS_ROOT="$GTB_ROOT/${REPO_NAME}-ac"
     local TEST_OUTPUT_FILE='/tmp/gtb_gradle_test_output.log'
 
-    [[ -d $HOMEWORK_ROOT ]] || error "Cannot find homework: $HOMEWORK_ROOT"
-    [[ -d $HOMEWORK_TESTS_ROOT ]] || error "Cannot find homework tests: $HOMEWORK_TESTS_ROOT"
+    [[ -d $HOMEWORK_ROOT ]] || fail "Cannot find homework: $HOMEWORK_ROOT"
+    [[ -d $HOMEWORK_TESTS_ROOT ]] || fail "Cannot find homework tests: $HOMEWORK_TESTS_ROOT"
 
     info "Start running acceptance tests..."
     ( cd $HOMEWORK_TESTS_ROOT && \
