feat: add stduent org|repo open

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -818,7 +818,6 @@ _gtb_check_student_org_for_trainer_role() {
             fi
         fi
     done < $GTB_STUDENTS_FILE | sort -r | column -s'|' -t
-
 }
 
 _gtb_student_org_check() {
@@ -836,8 +835,25 @@ _gtb_student_org_check() {
     _gtb_check_student_org_for_trainer_role "$@"
 }
 
+_gtb_student_org_open() {
+    if [[ $# -eq 0 ]]; then
+        fail 'At least one filter is required to match student with name, term, or tags, etc. (e.g. gtb student org open zhang.san)'
+    fi
+
+    while read -r FULLNAME ORG TERM_NAME TAGS
+    do
+        if echo "$TERM_NAME" | grep --silent "$GTB_TERM"
+        then
+            if echo "$*" | grep --silent "\<${FULLNAME}\>" || echo "$*" | grep --silent "\<${ORG}\>" || echo "$TAGS" | grep --silent "\<$1\>"
+            then
+                open "https://github.com/$ORG"
+            fi
+        fi
+    done < $GTB_STUDENTS_FILE
+}
+
 _gtb_student_org() {
-    if ! echo $1 | grep --silent '^\(invite\|check\|join\)$'; then
+    if ! echo $1 | grep --silent '^\(open\|check\|invite\|join\)$'; then
         set -- check "$@"
     fi
 
@@ -1056,8 +1072,28 @@ _gtb_student_repo_show() {
     done < $GTB_STUDENTS_FILE
 }
 
+_gtb_student_repo_open() {
+    local REPO_NAME=${1:?Repo name is required!}
+    shift
+
+    if [[ $# -eq 0 ]]; then
+        fail 'At least one filter is required to match student with name, term, or tags, etc. (e.g. gtb student repo open bronze-java-level-1 zhang.san)'
+    fi
+
+    while read -r FULLNAME ORG TERM_NAME TAGS
+    do
+        if echo "$TERM_NAME" | grep --silent "$GTB_TERM"
+        then
+            if echo "$*" | grep --silent "\<${FULLNAME}\>" || echo "$*" | grep --silent "\<${ORG}\>" || echo "$TAGS" | grep --silent "\<$1\>"
+            then
+                open "https://github.com/$ORG/$REPO_NAME"
+            fi
+        fi
+    done < $GTB_STUDENTS_FILE
+}
+
 _gtb_student_repo() {
-    if ! echo $1 | grep --silent '^\(show\|list\|create\|delete\)$'; then
+    if ! echo $1 | grep --silent '^\(show\|list\|create\|delete\|open\)$'; then
         set -- list "$@"
     fi
 
