feat: add retry when gh api get repo commit failed to avoid TLS handshake timeout issue

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -661,18 +661,28 @@ gh_show_org_repo_commit() {
     local COMMIT_REF=${3:?Commit ref is required!}
 
     local ENDPOINT="/repos/$ORG/$REPO_NAME/commits/$COMMIT_REF"
-    local OUTPUT="$ORG $REPO_NAME"
 
-    run "gh api $ENDPOINT 1>/dev/null $(_gtb_mute_stderr)"
+    local -ir RETRY=3
+    local -ir RETRY_INTERVAL=3
+    local RESULT
+    local OUTPUT
 
-    local result=$?
-    if [[ $result -eq 0 ]]; then
-        echo "OK" $ORG
-    else
-        echo "ERROR" $ORG
-    fi
+    for i in  $(seq 1 "$RETRY"); do
+        if [[ $i -gt 1 ]]; then
+            sleep "$RETRY_INTERVAL"
+        fi
 
-    return $result
+        run "gh api $ENDPOINT 1>/dev/null $(_gtb_mute_stderr)"
+        RESULT=$?
+
+        if [[ $RESULT -eq 0 ]]; then
+            echo "OK" $ORG
+            return 0
+        fi
+    done
+
+    echo "ERROR" $ORG
+    return $RESULT
 }
 
 gh_show_org_repo() {
