feat: exit with non-zero code if fail to add any members to card

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -3144,7 +3144,14 @@ _gtb_trello_card_member_add() {
             $GTB_PARALLEL_OPT_PROGRESS_BAR \
             "_gtb_trello_api --method 'POST' '/cards/${GTB_TRELLO_CARD_ID}/idMembers?value={1}' </dev/null 1>/dev/null 2>&1"
 
-    _gtb_trello_card_member_list
+    local -r MEMBER_LIST="$(_gtb_trello_card_member_list)"
+    echo "${MEMBER_LIST}"
+
+    while read -r MEMBER_ID HINT; do
+        if ! $GTB_GREP --silent "${MEMBER_ID}" <(echo "${MEMBER_LIST}"); then
+            fail "failed to add '${HINT}' to card!"
+        fi
+    done < <(trello_member_id "$@")
 }
 
 _gtb_trello_card_member_list() {
