feat: gtb student repo pick support multiple jobs now

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -1560,14 +1560,15 @@ _gtb_student_repo_pick() {
     shift
 
     if [[ 0 -eq $# ]]; then
-        fail 'error: refs to pick is not provided. (e.g. gtb student repo pick bronze-java-level-1 extended-tests)'
+        fail 'error: refs to pick is not provided. (e.g. extended-tests, fix-out-of-memory-issue, origin/fix-package-json-name)'
     fi
 
-    # introduce --filters a,b,c so we can skip updating local repo while no students matched the filters
-    _gtb_update_default_repo $REPO_NAME
+    header "Clone repo $REPO_NAME..."
+    _gtb_clone_default_repo $REPO_NAME
 
     run "cd $(_gtb_default_repo_dir $REPO_NAME)"
 
+    header "Collect refs to pick..."
     local commits_to_pick=''
     while [[ $# -gt 0 ]]; do
         local ref=$1
@@ -1584,32 +1585,69 @@ _gtb_student_repo_pick() {
         fail 'error: commits to be picked is not provided. (e.g. gtb student repo pick bronze-java-level-1 extended-tests)'
     fi
 
-    local student_lines
-    local students_count
-    student_lines=$(_gtb_filter_students "$@")
-    students_count=$(_gtb_count_lines "$student_lines")
+    header "Filter students..."
+    local student_lines=$(_gtb_filter_students "$@")
+    local students_count=$(_gtb_count_lines "$student_lines")
 
     [[ $students_count -eq 0 ]] && fail "error: no students matched by filters: '$@'"
 
-    echo "$student_lines" | while read -r FULLNAME ORG TERM_NAME TAGS
-    do
-        local retry_times=$GTB_MAX_RETRY_TIMES_REPO_PICK
-        local result=110
+    header "Add students' repo as remote..."
+    local result_add_remote=$(echo "$student_lines" \
+        | _gtb_cuts 1-2 \
+        | env_parallel --jobs 1 --colsep ' ' --bar --linebuffer "_gtb_add_student_repo_as_remote {2} $REPO_NAME $(_gtb_mute_stderr)" \
+        | sort \
+        | _gtb_cuts 3)
 
-        while [[ $retry_times -gt 0 && $result -gt 100 ]]; do
-            msg=$(_gtb_pick_and_push_commits $ORG $REPO_NAME $commits_to_pick)
-            result=$?
-            (( retry_times-- ))
-        done
+    header "Fetch all remotes..."
+    local result_fetch_remote=$(echo "$student_lines" \
+        | _gtb_cuts 1-2 \
+        | env_parallel --jobs $JOBS --colsep ' ' --bar --linebuffer "_gtb_fetch_remote $REPO_NAME {2} $(_gtb_mute_stderr)" \
+        | sort -k2 \
+        | _gtb_cuts 1)
 
-        if [[ $result -eq 0 && -n $WORKFLOW_FILENAME ]]
-        then
-            gh_run_repo_workflow $ORG $REPO_NAME $WORKFLOW_FILENAME
-        fi
+    header "Create local branches..."
+    local result_create_branch=$(echo "$student_lines" \
+        | _gtb_cuts 1-2 \
+        | env_parallel --jobs 1 --colsep ' ' --bar --linebuffer "_gtb_create_local_branch $REPO_NAME {2} $(_gtb_mute_stderr)" \
+        | sort -k2 \
+        | _gtb_cuts 1)
 
-        [[ $result -eq 0 ]] && font_color=28 || font_color=161
-        logtf $font_color "$FULLNAME|$msg"
-    done | _gtb_pv $students_count | _gtb_tee1 | sort | _gtb_tabularize 'SUMMARY'
+    header "Pick refs..."
+    local result_pick_ref=$(echo "$student_lines" \
+        | _gtb_cuts 1-2 \
+        | env_parallel --jobs 1 --colsep ' ' --bar --linebuffer "_gtb_pick_refs $REPO_NAME {2} $commits_to_pick $(_gtb_mute_stderr)" \
+        | sort -k2 \
+        | _gtb_cuts 1)
+
+    header "Push to remotes..."
+    local result_push_to_remote=$(echo "$student_lines" \
+        | _gtb_cuts 1-2 \
+        | env_parallel --jobs $JOBS --colsep ' ' --bar --linebuffer "_gtb_push_master $REPO_NAME {2} $(_gtb_mute_stderr)" \
+        | sort -k2 \
+        | _gtb_cuts 1)
+
+    if [[ -n $WORKFLOW_FILENAME ]]
+    then
+        header "Run workflows..."
+        local result_run_workflow=$(echo "$student_lines" \
+            | _gtb_cuts 1-2 \
+            | env_parallel --jobs $JOBS --colsep ' ' --bar --linebuffer "gh_run_repo_workflow {2} $REPO_NAME $WORKFLOW_FILENAME" \
+            | sort -k2 \
+            | _gtb_cuts 1,3)
+    fi
+
+    {
+        echo "ID ORG ADD_REMOTE FETCH_REMOTE CREATE_BRANCH PICK_REF PUSH_TO_REMOTE RUN_WORKFLOW ACTIONS_URL"
+        pr -m -t -s' ' \
+            <(echo "$student_lines" | _gtb_cuts 2 | sort) \
+            <(echo "$result_add_remote") \
+            <(echo "$result_fetch_remote") \
+            <(echo "$result_create_branch") \
+            <(echo "$result_pick_ref") \
+            <(echo "$result_push_to_remote") \
+            <(echo "$result_run_workflow") \
+            | nl | tr '\t' ' ' | tr -s ' ' | sed 's/^ //'
+    } | column -t
 }
 
 _gtb_student_repo_delete() {
@@ -1887,6 +1925,83 @@ _gtb_add_student_repo_as_remote() {
         echo "$* $SYMBOL_OK"
     else
         echo "$* $SYMBOL_ERROR"
+    fi
+}
+
+_gtb_fetch_remote() {
+    local REPO_NAME=${1:?Repo name is required!}
+    local ORG=${2:?org name is required!}
+
+    local REPO_DIR=$(_gtb_default_repo_dir $REPO_NAME)
+    [[ -d $REPO_DIR ]] || fail "Cannot find local directory for repo '$REPO_NAME'!"
+
+    run "cd $REPO_DIR"
+    run "git fetch $ORG" >&2
+
+    if [[ $? -eq 0 ]]
+    then
+        echo "$SYMBOL_OK $ORG"
+    else
+        echo "$SYMBOL_ERROR $ORG"
+    fi
+}
+
+_gtb_create_local_branch() {
+    local REPO_NAME=${1:?Repo name is required!}
+    local ORG=${2:?org name is required!}
+
+    local REPO_DIR=$(_gtb_default_repo_dir $REPO_NAME)
+    [[ -d $REPO_DIR ]] || fail "Cannot find local directory for repo '$REPO_NAME'!"
+
+    run "cd $REPO_DIR"
+    run "git checkout -b $ORG $ORG/master" >&2
+
+    if [[ $? -eq 0 ]]
+    then
+        echo "$SYMBOL_OK $ORG"
+    else
+        echo "$SYMBOL_ERROR $ORG"
+    fi
+}
+
+_gtb_pick_refs() {
+    local REPO_NAME=${1:?Repo name is required!}
+    local ORG=${2:?org name is required!}
+
+    shift 2
+
+    local REPO_DIR=$(_gtb_default_repo_dir $REPO_NAME)
+    [[ -d $REPO_DIR ]] || fail "Cannot find local directory for repo '$REPO_NAME'!"
+
+    run "cd $REPO_DIR"
+    run "git cherry-pick --abort" >&2
+    run "git checkout $ORG" >&2 \
+        && run "git cherry-pick --ff --allow-empty --keep-redundant-commits $*" >&2
+
+    if [[ $? -eq 0 ]]
+    then
+        echo "$SYMBOL_OK $ORG"
+    else
+        run "git cherry-pick --abort" >&2
+        echo "$SYMBOL_ERROR $ORG"
+    fi
+}
+
+_gtb_push_master() {
+    local REPO_NAME=${1:?Repo name is required!}
+    local ORG=${2:?org name is required!}
+
+    local REPO_DIR=$(_gtb_default_repo_dir $REPO_NAME)
+    [[ -d $REPO_DIR ]] || fail "Cannot find local directory for repo '$REPO_NAME'!"
+
+    run "cd $REPO_DIR"
+    run "git push $ORG $ORG:master" >&2
+
+    if [[ $? -eq 0 ]]
+    then
+        echo "$SYMBOL_OK $ORG"
+    else
+        echo "$SYMBOL_ERROR $ORG"
     fi
 }
 
