refactor: run _gtb_add_student_repo_as_remote() in parallel

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -1867,7 +1867,9 @@ _gtb_remove_remote_student_repo() {
 }
 
 _gtb_add_student_repo_as_remote() {
-    local REPO_NAME=${1:?Repo name is required!}
+    local ORG=${1:?org name is required!}
+    local REPO_NAME=${2:?Repo name is required!}
+
     local REPO_DIR=$(_gtb_default_repo_dir $REPO_NAME)
     [[ -d $REPO_DIR ]] || fail "Cannot find local directory for repo '$REPO_NAME'!"
 
@@ -1875,15 +1877,17 @@ _gtb_add_student_repo_as_remote() {
 
     local REMOTES=$(run "git remote")
 
-    while read -r ORG REPO_NAME TERM_NAME FULLNAME
-    do
-        if echo "$REMOTES" | grep -v --silent "$ORG"; then
-            local repo_url="git@github.com:$ORG/${REPO_NAME}.git"
-            run "git remote add $ORG $repo_url"
-        fi
+    if ! echo "$REMOTES" | grep --silent "$ORG"; then
+        local repo_url="git@github.com:$ORG/${REPO_NAME}.git"
+        run "git remote add $ORG $repo_url" >&2
+    fi
 
-        echo $ORG $REPO_NAME $TERM_NAME $FULLNAME
-    done
+    if [[ $? -eq 0 ]]
+    then
+        echo "$* $SYMBOL_OK"
+    else
+        echo "$* $SYMBOL_ERROR"
+    fi
 }
 
 _gtb_delete_existing_remote() {
@@ -1955,7 +1959,7 @@ _gtb_repo_publish() {
         <(echo "$student_lines" | cut -d' ' -f1-3 \
             | _gtb_delete_existing_remote $REPO_NAME \
             | env_parallel --jobs $JOBS --colsep ' ' --bar --linebuffer _gtb_create_repo_in_student_org {1} {2} {3} {4} \
-            | _gtb_add_student_repo_as_remote $REPO_NAME \
+            | env_parallel --jobs 1 --colsep ' ' --bar --linebuffer _gtb_add_student_repo_as_remote {1} {2} {3} {4} \
             | env_parallel --jobs $MAX_JOBS --colsep ' ' --bar --linebuffer gh_init_repo_secrets {1} {2} {3} {4} \
             | env_parallel --jobs $JOBS --colsep ' ' --bar --linebuffer _gtb_push_to_student_repo {1} {2} \
             | sort -k1) \
