feat: add new command: gtb dashboard student && gtb dashboard submission

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -136,6 +136,15 @@ _gtb_tabularize() {
     fi
 }
 
+_gtb_table_format() {
+    if [[ "$GTB_RAW" == "true" ]]
+    then
+        cat
+    else
+        cat | column -t | cat -n
+    fi
+}
+
 _gtb_pv() {
     cat | pv -tbelSs $1 -i 0.3 -N "total is: $1 current is"
 }
@@ -155,6 +164,16 @@ _gtb_count() {
         echo "$input" | sort | uniq -c | sed -E 's/^ +//g'
         echo -e "$lines_count TOTAL"
     } | column -t
+}
+
+_gtb_quotes_line() {
+    local QUOTE="${1:-\"}"
+    cat | sed -E "s/^/$QUOTE/;s/$/$QUOTE/"
+}
+
+_gtb_join_lines() {
+    local SEPARATOR="${1:-,}"
+    cat | paste -s -d, - | tr -d '\n'
 }
 
 _gtb_default_repo_dir() {
@@ -2409,14 +2428,319 @@ _gtb_config() {
     _gtb_run_subcommand ${FUNCNAME[0]#_gtb_} "$@"
 }
 
+_gtb_dashboard_list_students() {
+    run "http --print b GET $GTB_DASHBOARD_ADDRESS/terms/${GTB_TERM}/students/list" \
+        | jq -r '.[] | .gtbTerm.name, .gtbUsername, .displayName, .githubUsername, .id' \
+        | paste -d' ' - - - - - \
+        | sort -k1,2
+}
+
+_gtb_dashboard_search_student() {
+    run "http --print b GET $GTB_DASHBOARD_ADDRESS/terms/${GTB_TERM}/students/search?gtbUsername=${1}" \
+        | jq .
+}
+
+_gtb_dashboard_deactivate_student() {
+    local FULLNAME=${1:?Trainee fullname is required! (e.g. zhang.san, li.si, etc.)}
+
+    local id=$(run "_gtb_dashboard_search_student '$FULLNAME' | jq -r '.id'")
+
+    local result=$(run "http --print b --auth 'user:$GTB_SONAR_TOKEN' PUT '$GTB_DASHBOARD_ADDRESS/terms/${GTB_TERM}/students/${id}/deactivate' | jq -r '.deactivated'")
+
+    if [[ "$result" == "true" ]]; then
+        echo "✅ $FULLNAME"
+        return 0
+    fi
+
+    echo "❌ $FULLNAME"
+    return 1
+}
+
+_gtb_dashboard_list_submissions() {
+    run "http --print b GET $GTB_DASHBOARD_ADDRESS/terms/${GTB_TERM}/submissions" \
+        | jq -r '[.[].submissions[]] | .[] | .assignmentType, .repository, .gtbUsername, .displayName, .firstMeasurementTestStatus, .firstMeasurementScore, .finalMeasurementTestStatus, .finalMeasurementScore, .startTime, .firstMeasurementTime, .finalMeasurementTime' \
+        | paste -d' ' - - - - - - - - - - - \
+        | sort -k1,1 -k9,9
+}
+
+_gtb_dashboard_create_submission() {
+    local ASSIGNMENT_KEY="${1:?assignmentKey is required!}"
+    local START_TIME="${2:?startTime is required!}"
+    local FIRST_MEASUREMENT_TIME="${3:?firstMeasurementTime is required!}"
+    local FINAL_MEASUREMENT_TIME="${4:?finalMeasurementTime is required!}"
+    local USERNAMES="${5:?gtbUsernames is required!}"
+
+    local PAYLOAD_JSON_FILE="/tmp/gtb-create-submission-$ASSIGNMENT_KEY-$$.json"
+
+    cat <<EOF > "$PAYLOAD_JSON_FILE"
+{
+    "assignmentKey": "$ASSIGNMENT_KEY",
+    "startTime": "$START_TIME",
+    "firstMeasurementTime": "$FIRST_MEASUREMENT_TIME",
+    "finalMeasurementTime": "$FINAL_MEASUREMENT_TIME",
+    "gtbUsernames":[$USERNAMES]
+}
+EOF
+    http --print=b \
+        --auth "user:$GTB_SONAR_TOKEN" \
+        PUT "$GTB_DASHBOARD_ADDRESS/terms/$GTB_TERM/submissions" \
+        < "$PAYLOAD_JSON_FILE"
+}
+
+_gtb_dashboard_delete_submission() {
+    local ASSIGNMENT_KEY="${1:?assignmentKey is required!}"
+    local USERNAME="${2:?gtbUsername is required!}"
+
+    run "http --auth 'user:$GTB_SONAR_TOKEN' DELETE '$GTB_DASHBOARD_ADDRESS/terms/${GTB_TERM}/submissions?assignmentKey=${ASSIGNMENT_KEY}&gtbUsername=${USERNAME}'"
+
+    echo "$ASSIGNMENT_KEY $USERNAME"
+}
+
+_gtb_dashboard_submission_remove() {
+    GTB_RAW="true"
+    local found_submissions="$(_gtb_dashboard_submission_list "$@")"
+    local found_submissions_count="$(_gtb_count_lines "$found_submissions")"
+
+    if [[ "$found_submissions_count" -eq 0 ]]
+    then
+        info 'No submissions found.'
+        exit 0
+    fi
+
+    GTB_RAW="false"
+    echo "$found_submissions" | _gtb_table_format
+
+    read -p "about to DELETE submissions above? (y|n) " -n 1 -r
+    if [[ ! $REPLY =~ ^[Yy]$ ]]
+    then
+        return 1
+    fi
+
+    echo
+    info "delete submissions..."
+    echo "$found_submissions" \
+        | _gtb_cuts 2,3 \
+        | env_parallel \
+            --colsep ' ' \
+            --linebuffer \
+            --jobs $JOBS \
+            --bar \
+            _gtb_dashboard_delete_submission "{1}" "{2}" \
+        | sort \
+        | cat -n
+
+    echo
+    info "query submissions..."
+    GTB_RAW="true"
+    local left_submissions="$(_gtb_dashboard_submission_list "$@")"
+    local left_submissions_count=$(_gtb_count_lines "$left_submissions")
+
+    if [[ "$left_submissions_count" -gt 0 ]]
+    then
+        GTB_RAW="false"
+        echo
+        error "failed to delete following $left_submissions_count submissions:"
+        echo "$left_submissions" | _gtb_table_format
+        exit 1
+    fi
+
+    info "All specified submissions deleted!"
+}
+
+_gtb_dashboard_submission_delete() {
+    _gtb_dashboard_submission_remove "$@"
+}
+
+_gtb_dashboard_submission_create() {
+    # gtb dashboard submission add --repo bronze-java-level-1 --start 2021041609 --basic 8H --refactor 14d w02fri1
+    local REPO_NAME=${GTB_REPO:?repo name should be provided using --repo option.}
+    local START_AT=${GTB_START_AT:?start time should be provided using --start optoin, e.g. 2021041609}
+    local DURATION_BASIC=${GTB_DURATION_BASIC:-$GTB_DURATION_REFACTOR}
+    local DURATION_REFACTOR=${GTB_DURATION_REFACTOR:?refactoring duration should be specified using --refactor option, e.g. 14d, 21d, 8h, 10h, etc}
+
+    DURATION_BASIC=$(echo $DURATION_BASIC | tr 'h' 'H')
+    DURATION_REFACTOR=$(echo $DURATION_REFACTOR | tr 'h' 'H')
+
+    # date -v4m -v16d -v9H -v0M -v0S '+%Y-%m-%dT%H:%M:%S%z' | sed -E 's/(..)$/:\1/'
+    # 2021-04-16T09:00:00+08:00
+    local start_time=$(date \
+        -v$(echo $START_AT | cut -c1-4)y \
+        -v$(echo $START_AT | cut -c5-6)m \
+        -v$(echo $START_AT | cut -c7-8)d \
+        -v$(echo $START_AT | cut -c9-10)H \
+        -v0M \
+        -v0S \
+        '+%Y-%m-%dT%H:%M:%S%z' | sed -E 's/(..)$/:\1/')
+    local first_measurement_time=$(date \
+        -v+${DURATION_BASIC} \
+        -jf '%Y-%m-%dT%H:%M:%S%z' "$(echo $start_time | sed -E 's/(.*):(..)$/\1\2/')" \
+        '+%Y-%m-%dT%H:%M:%S%z' | sed -E 's/(..)$/:\1/')
+    local final_measurement_time=$(date \
+        -v+${DURATION_REFACTOR} \
+        -jf '%Y-%m-%dT%H:%M:%S%z' "$(echo $start_time | sed -E 's/(.*):(..)$/\1\2/')" \
+        '+%Y-%m-%dT%H:%M:%S%z' | sed -E 's/(..)$/:\1/')
+
+    local student_lines=$(_gtb_filter_students "$@")
+    local students_count=$(_gtb_count_lines "$student_lines")
+
+    assert_not_empty "error: cannot find any students with filters: '$@'!" "$student_lines"
+
+    echo "$student_lines" | _gtb_cuts 3,2,1,7,8,9 | _gtb_table_format
+    read -p "about to create submission for $students_count students above? (y|n) " -n 1 -r
+    if [[ ! $REPLY =~ ^[Yy]$ ]]
+    then
+        return 1
+    fi
+
+    echo
+    info "submission information:"
+    echo "$REPO_NAME"
+    echo "$start_time"
+    echo "$first_measurement_time"
+    echo "$final_measurement_time"
+    read -p "please confirm submission information above? (y|n) " -n 1 -r
+    if [[ ! $REPLY =~ ^[Yy]$ ]]
+    then
+        return 1
+    fi
+
+    local fullnames="$(echo "$student_lines" | _gtb_cuts 1 | _gtb_quotes_line | _gtb_join_lines)"
+
+    echo
+    info "create submissions..."
+    _gtb_dashboard_create_submission \
+        "$REPO_NAME" \
+        "$start_time" \
+        "$first_measurement_time" \
+        "$final_measurement_time" \
+        "$fullnames"
+
+    echo
+    info "query created submissions..."
+    GTB_RAW="true"
+    local created_submissions="$(_gtb_dashboard_submission_list "$@")"
+    local created_submissions_count=$(_gtb_count_lines "$created_submissions")
+
+    GTB_RAW="false"
+    echo "$created_submissions" | _gtb_table_format
+
+    if [[ "$created_submissions_count" -ne "$students_count" ]]
+    then
+        echo
+        error "error: $(($students_count - $created_submissions_count)) submissions are missing!"
+        exit 1
+    fi
+}
+
+_gtb_dashboard_submission_add() {
+    _gtb_dashboard_submission_create "$@"
+}
+
+_gtb_dashboard_submission_list() {
+    local student_lines=$(_gtb_filter_students "$@")
+    local students_count=$(_gtb_count_lines "$student_lines")
+
+    assert_not_empty "error: cannot find any students with filters: '$@'!" "$student_lines"
+
+    local submissions="$(_gtb_dashboard_list_submissions)"
+
+    local REPO_NAME=${GTB_REPO:-}
+    if [[ ! -z "$REPO_NAME" ]]
+    then
+        submissions="$(echo "$submissions" | grep --color=never -w $REPO_NAME)"
+    fi
+
+    local fullnames="$(echo "$student_lines" | _gtb_cuts 1 | paste -s -d'|' -)"
+    if [[ ! -z "$fullnames" ]]
+    then
+        submissions="$(echo "$submissions" | grep --color=never -w -E $fullnames)"
+    fi
+
+    echo "$submissions" | _gtb_table_format
+}
+
+_gtb_dashboard_submission() {
+    assert_students_file_exists
+
+    if ! echo $1 | grep --silent '^\(list\|create\|add\|remove\|delete\)$'; then
+        set -- list "$@"
+    fi
+
+    _gtb_run_subcommand ${FUNCNAME[0]#_gtb_} "$@"
+}
+
+_gtb_dashboard_sub() {
+    _gtb_dashboard_submission "$@"
+}
+
+_gtb_dashboard_student_deactivate() {
+    local student_lines=$(_gtb_filter_students "$@")
+    local students_count=$(_gtb_count_lines "$student_lines")
+
+    assert_not_empty "error: cannot find any students with filters: '$@'!" "$student_lines"
+
+    echo "$student_lines" \
+        | _gtb_cuts 2,4,7 \
+        | sort \
+        | column -t \
+        | cat -n
+
+    read -p "about to DELETE ${students_count} students from $GTB_ORG? (y|n) " -n 1 -r
+    if [[ ! $REPLY =~ ^[Yy]$ ]]
+    then
+        return 1
+    fi
+
+    echo "$student_lines" \
+        | _gtb_cuts 1 \
+        | env_parallel \
+            --linebuffer \
+            --jobs $JOBS \
+            --bar \
+            _gtb_dashboard_deactivate_student {} \
+        | sort \
+        | cat -n
+}
+
+_gtb_dashboard_student_search() {
+    local FULLNAME=${1:?Trainee fullname is required! (e.g. zhang.san, li.si, etc.)}
+    _gtb_dashboard_search_student "$FULLNAME"
+}
+
+_gtb_dashboard_student_list() {
+    _gtb_dashboard_list_students \
+        | column -t \
+        | cat -n
+}
+
+_gtb_dashboard_student() {
+    if ! echo $1 | grep --silent '^\(list\|search\|deactivate\)$'; then
+        set -- list "$@"
+    fi
+
+    _gtb_run_subcommand ${FUNCNAME[0]#_gtb_} "$@"
+}
+
+_gtb_dashboard_st() {
+    _gtb_dashboard_student "$@"
+}
+
+_gtb_dashboard_open() {
+    run "open ${GTB_DASHBOARD_ADDRESS%/api}?term=${GTB_TERM}"
+}
+
 _gtb_dashboard() {
     assert_students_file_exists
 
-    if ! echo $1 | grep --silent '^\(open\|student\|submission\)$'; then
+    if ! echo $1 | grep --silent '^\(open\|student\|st\|submission\|sub\)$'; then
         set -- open "$@"
     fi
 
     _gtb_run_subcommand ${FUNCNAME[0]#_gtb_} "$@"
+}
+
+_gtb_dash() {
+    _gtb_dashboard "$@"
 }
 
 _gtb_comments() {
@@ -2725,6 +3049,38 @@ while (( "$#" )); do
                 shift 2
             else
                 fail "Error: Position of new tag specified by '$1' is missing"
+            fi
+            ;;
+        --repo)
+            if [[ -n "$2" ]] && [[ ${2:0:1} != "-" ]]; then
+                GTB_REPO=$2
+                shift 2
+            else
+                fail "Error: repository name specified by '$1' is missing"
+            fi
+            ;;
+        --start)
+            if [[ -n "$2" ]] && [[ ${2:0:1} != "-" ]]; then
+                GTB_START_AT=$2
+                shift 2
+            else
+                fail "Error: evaluation start_at time specified by '$1' is missing, e.g. 2021041609"
+            fi
+            ;;
+        --basic)
+            if [[ -n "$2" ]] && [[ ${2:0:1} != "-" ]]; then
+                GTB_DURATION_BASIC=$2
+                shift 2
+            else
+                fail "Error: evaluation basic part duration specified by '$1' is missing, e.g. 8h, 10h, 7d, 14d"
+            fi
+            ;;
+        --refactor)
+            if [[ -n "$2" ]] && [[ ${2:0:1} != "-" ]]; then
+                GTB_DURATION_REFACTOR=$2
+                shift 2
+            else
+                fail "Error: evaluation refactor part duration specified by '$1' is missing, e.g. 14d, 21d, 8h, 10h"
             fi
             ;;
         --raw)
