feat: clone config repo to $GTB_ROOT while running gtb init

diff --git a/gtb b/gtb
--- a/gtb
+++ b/gtb
@@ -2,8 +2,10 @@
 
 GTB_ROOT="${GTB_ROOT:-$HOME/code/gtb}"
 GTB_TERM="${GTB_TERM:?GTB_TERM should be set! (term01, term02, etc.)}"
-GTB_TRAINERS_FILE="${GTB_TRAINERS_FILE:-$GTB_ROOT/trainers.txt}"
-GTB_STUDENTS_FILE="${GTB_STUDENTS_FILE:-$GTB_ROOT/students.txt}"
+GTB_CONFIG_REPO=config
+GTB_CONFIG_DIR="$GTB_ROOT/$GTB_CONFIG_REPO"
+GTB_TRAINERS_FILE="${GTB_TRAINERS_FILE:-$GTB_CONFIG_DIR/trainers.txt}"
+GTB_STUDENTS_FILE="${GTB_STUDENTS_FILE:-$GTB_CONFIG_DIR/students.txt}"
 GTB_SONAR_ADDRESS="${GTB_SONAR_ADDRESS:?Please set env GTB_SONAR_ADDRESS correctly! (P.S. Ask ZHANG Zhe)}"
 GTB_SONAR_TOKEN="${GTB_SONAR_TOKEN:?Please set env GTB_SONAR_TOKEN correctly! (P.S. Ask ZHANG Zhe)}"
 GTB_RANDOM_LIST_FILE="/tmp/gtb_random_list.txt"
@@ -475,7 +477,9 @@ assert_not_empty() {
 assert_trainers_file_exists() {
     if [[ ! -f $GTB_TRAINERS_FILE ]]
     then
-        fail "Cannot find trainers file: '$GTB_TRAINERS_FILE'."
+        error "Cannot find trainers file: '$GTB_TRAINERS_FILE'."
+        error "If you upgrade from the old versions, please run \`gtb init\` to clone config repo."
+        exit 1
     fi
 }
 
@@ -483,6 +487,7 @@ assert_students_file_exists() {
     if [[ ! -f $GTB_STUDENTS_FILE ]]
     then
         error "Cannot find students file: '$GTB_STUDENTS_FILE'."
+        error "If you upgrade from the old versions, please run \`gtb init\` to clone config repo."
         exit 1
     fi
 }
@@ -1490,17 +1495,7 @@ _gtb_init() {
     mkdir -p $GTB_ROOT/$GTB_REPOS_DIR
     mkdir -p $GTB_ROOT/$GTB_TERMS_DIR
 
-    if [[ ! -f $GTB_TRAINERS_FILE ]]
-    then
-        touch $GTB_TRAINERS_FILE
-        info "Created trainers file: '$GTB_TRAINERS_FILE'."
-    fi
-
-    if [[ ! -f $GTB_STUDENTS_FILE ]]
-    then
-        touch $GTB_STUDENTS_FILE
-        info "Created students file: '$GTB_STUDENTS_FILE'."
-    fi
+    [[ -d $GTB_CONFIG_DIR ]] || gh_clone_repo GTB-training $GTB_CONFIG_REPO $GTB_CONFIG_DIR
 }
 
 _gtb_help() {
